/// <reference path="globals/agenda/index.d.ts" />
/// <reference path="globals/bluebird/index.d.ts" />
/// <reference path="globals/body-parser/index.d.ts" />
//. <reference path="globals/core-js/index.d.ts" />
/// <reference path="globals/express-serve-static-core/index.d.ts" />
/// <reference path="globals/express/index.d.ts" />
// <reference path="globals/jasmine/index.d.ts" />
/// <reference path="../node_modules/@types/jasmine/index.d.ts" />
/// <reference path="globals/lodash/index.d.ts" />
/// <reference path="globals/mime/index.d.ts" />
/// <reference path="globals/mongodb/index.d.ts" />
/// <reference path="globals/mongoose/index.d.ts" />
//// <reference path="globals/node/index.d.ts" />
// / <reference path="globals/phantomjs/index.d.ts" />
/// <reference path="globals/sequelize/index.d.ts" />
/// <reference path="globals/serve-static/index.d.ts" />
/// <reference path="globals/validator/index.d.ts" />
